### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by myeviltwin** [KioCoan/KiPuzzle#2]
hi,
I'm impressed with your work with KiPuzzle.  Very cool.  Could you provide a license in the repo?

https://github.com/blog/1530-choosing-an-open-source-license

**Comment by HasanEdain** [comment]
This is not my work, it is a fork of another authors. for any contributions I have made, they should fall under the original author's license.

**Comment by myeviltwin** [comment]
@KioCoan could you share your license in the repo?

**Comment by KioCoan** [comment]
@myeviltwin Thanks for your request.

I was busy and didn't see this notification earlier, Sorry. 

I added the licence file. Thanks.
